# ------------------------------------------------------------------------------
# envs/distributed/docker-compose.yml
# ------------------------------------------------------------------------------

# Host Docker Compose services for the "distributed" test environment.

version: "3.7"

services:

  # office network

  backup-director:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_backup-director
    hostname: backup-director
    volumes:
      - director-bacula-home:/var/lib/bacula/
    networks:
      office:
        ipv4_address: 10.0.0.101
    cap_add:
      - NET_ADMIN

  backup-storage:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_backup-storage
    hostname: backup-director
    volumes:
      - storage-bacula-home:/var/lib/bacula/
    networks:
      office:
        ipv4_address: 10.0.0.102
    cap_add:
      - NET_ADMIN

  caldav:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_caldav
    hostname: caldav
    networks:
      office:
        ipv4_address: 10.0.0.103
    cap_add:
      - NET_ADMIN

  database-internal:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_database-internal
    hostname: database-internal
    networks:
      office:
        ipv4_address: 10.0.0.104
    cap_add:
      - NET_ADMIN

  dns-internal:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_dns-internal
    hostname: dns-internal
    networks:
      office:
        ipv4_address: 10.0.0.105
    cap_add:
      - NET_ADMIN

  dynamic-dns:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_dynamic-dns
    hostname: dynamic-dns
    networks:
      office:
        ipv4_address: 10.0.0.106
    cap_add:
      - NET_ADMIN

  mail-certificates:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_mail-certificates
    hostname: mail-certificates
    networks:
      office:
        ipv4_address: 10.0.0.107
    cap_add:
      - NET_ADMIN

  mail-internal:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    hostname: mail-internal
    container_name: services_mail-internal
    networks:
      office:
        ipv4_address: 10.0.0.108
    cap_add:
      - NET_ADMIN

  reverse-proxy-gateway:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_reverse-proxy-gateway
    hostname: reverse-proxy-gateway
    networks:
      office:
        ipv4_address: 10.0.0.109
    cap_add:
      - NET_ADMIN

  reverse-proxy-internal:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_reverse-proxy-internal
    hostname: reverse-proxy-internal
    networks:
      office:
        ipv4_address: 10.0.0.110
    cap_add:
      - NET_ADMIN

  wordpress-internal:
    build: build/sshd
    container_name: services_wordpress-internal
    image: varilink/services/ssh:bullseye
    hostname: wordpress-internal
    networks:
      office:
        ipv4_address: 10.0.0.111
    cap_add:
      - NET_ADMIN

  # internet

  database-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_database-external
    hostname: database-external
    networks:
      internet:
        ipv4_address: 10.0.1.101
    cap_add:
      - NET_ADMIN

  dns-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_dns-external
    hostname: dns-external
    networks:
      internet:
        ipv4_address: 10.0.1.102
    cap_add:
      - NET_ADMIN

  mail-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_mail-external
    hostname: mail-external
    networks:
      internet:
        ipv4_address: 10.0.1.103
    cap_add:
      - NET_ADMIN

  reverse-proxy-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_reverse-proxy-external
    hostname: reverse-proxy-external
    networks:
      internet:
        ipv4_address: 10.0.1.104
    cap_add:
      - NET_ADMIN

  wordpress-external:
    build: build/sshd
    image: varilink/services/ssh:bullseye
    container_name: services_wordpress-external
    hostname: wordpress-external
    networks:
      internet:
        ipv4_address: 10.0.1.105
    cap_add:
      - NET_ADMIN

volumes:
  director-bacula-home:
  storage-bacula-home:
