name: home.com
organisation: Mock-Up Home Organisation

# Default reverse proxy pass port to use when configuring this domain's web
# services. This can be overridden for an individual webhost below.
reverse_proxy_pass_port: 8080

# Details of each webhost that a web service for which a web service is to be
# deployed for this domain.
webhosts:
  - name: test
    reverse_proxy_host: wordpress-stack-internal
    wordpress_host: wordpress-stack-internal
    wordpress_database_host: wordpress-stack-internal
    wordpress_database_password: '%KHPfgUp%YB3zvte'
  - name: www
    reverse_proxy_host: reverse-proxy-external
    wordpress_host: wordpress-external
    wordpress_database_host: database-external
    wordpress_database_password: 'cPqWcKu&^whQ7Q2K'

# Details for Dynamic DNS updates for this domain.
linode_domain_id: 1860193
linode_dynamic_dns_domain_records:
  - 21720983 # test

# Users for which to configure an mail service for this domain.
users:
  - fname: "{{ home_domain_admin_user }}"
    lname: user1lname
    passwd: "{{ home_domain_admin_user_passwd }}"
  - fname: user2fname
    lname: user2lname
    passwd: user2passwd
