# ------------------------------------------------------------------------------
# envs/now/docker-compose.yml
# ------------------------------------------------------------------------------

# Docker Compose services that simulate the hosts of Varilink Computing Ltd
# services in the "now" test environment. The "now" test environment simulates
# our live environment in which our policy is to use the current Debian stable
# release.

version: "3.7"

services:

  # "office" Docker network

  dev:
    build: build/sshd
    image: varilink/services/sshd:bookworm
    container_name: services_dev
    hostname: dev
    networks:
      office:
        ipv4_address: 10.0.0.101
    cap_add:
      - NET_ADMIN

  gateway:
    build: build/sshd
    image: varilink/services/sshd:bookworm
    container_name: services_gateway
    hostname: gateway
    networks:
      office:
        ipv4_address: 10.0.0.102
    cap_add:
      - NET_ADMIN

  hub:
    build: build/sshd
    image: varilink/services/sshd:bookworm
    container_name: services_hub
    hostname: hub
    volumes:
      - bacula-home:/var/lib/bacula/
    networks:
      office:
        ipv4_address: 10.0.0.103
    cap_add:
      - NET_ADMIN

  # "internet" Docker network

  dns-external:
    build: build/sshd
    image: varilink/services/sshd:bookworm
    container_name: services_dns-external
    hostname: dns-external
    networks:
      internet:
        ipv4_address: 10.0.1.101
    cap_add:
      - NET_ADMIN

  mail:
    build: build/sshd
    image: varilink/services/sshd:bookworm
    container_name: services_mail
    hostname: mail
    volumes:
      - ./envs/now/sources.list:/etc/apt/sources.list
    networks:
      internet:
        ipv4_address: 10.0.1.102
    cap_add:
      - NET_ADMIN

  prod:
    build: build/sshd
    image: varilink/services/sshd:bookworm
    container_name: services_prod
    hostname: prod
    networks:
      internet:
        ipv4_address: 10.0.1.103
    cap_add:
      - NET_ADMIN

volumes:
  bacula-home:
