# ------------------------------------------------------------------------------
# my-roles/calendar/tasks/stop-radicale.yml
# ------------------------------------------------------------------------------

---

- name: Get the codename of the Debian release on this host
  ansible.builtin.command: lsb_release --codename --short
  register: lsb_release
  changed_when: false

- name: Test if the radicale process is running
  ansible.builtin.shell: |-
    {% if lsb_release.stdout == 'buster' %}
    pgrep -f '^/usr/bin/python3 /usr/bin/radicale -f$'
    {% elif lsb_release.stdout == 'bullseye' %}
    pgrep -f '^/usr/bin/python3 /usr/bin/radicale$'
    {% endif %}
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- name: Stop the radicale process
  ansible.builtin.shell: |-
    echo 'radicale   : Stopping' >> /var/local/services.log
    {% if lsb_release.stdout == 'buster' %}
    pkill -f '^/usr/bin/python3 /usr/bin/radicale -f$'
    {% elif lsb_release.stdout == 'bullseye' %}
    pkill -f '^/usr/bin/python3 /usr/bin/radicale$'
    {% endif %}

    n=0
    while [ $n -lt 3 ]; do
      sleep 3
      {% if lsb_release.stdout == 'buster' %}
      pgrep -f '^/usr/bin/python3 /usr/bin/radicale -f$' || \
        echo 'radicale   : Stopped' >> /var/local/services.log && break
      {% elif lsb_release.stdout == 'bullseye' %}
      pgrep -f '^/usr/bin/python3 /usr/bin/radicale$' || \
        echo 'radicale   : Stopped' >> /var/local/services.log && break
      {% endif %}
      let n=n+1
    done

    if [ $n -eq 3 ]; then
      echo 'radicale   : Failed to stop process' \
        >> /var/local/services.log
    fi
  args:
    executable: /bin/bash
  become: yes
  when: pgrep_result.rc == 0
