# ------------------------------------------------------------------------------
# docker-compose.yml
# ------------------------------------------------------------------------------

version: "3.7"
# This is the primary, and default, Docker Compose file for the project. It
# contains the networks and services definitions that form the base Compose file
# configuration for the project. This file is always the first in the Compose
# file path, whether we're using the distributed, now or to-be test environment.
# Other Compose files follow in the Compose file path, to modify these service
# definitions or add other ones.


networks:

  # We use the IPAM driver to allocate subnets to two Docker networks. These
  # emulate our office (internal) network and the Internet, by which we mean any
  # network that is external to our office network. This in turn allows us to
  # emulate our hybrid services architecture, that combines both Cloud and
  # on-premise hosts.

  office:
    ipam:
      config:
        - subnet: 10.0.0.0/24

  internet:
    ipam:
      config:
        - subnet: 10.0.1.0/24

services:

  # The definition of quite a number of Docker Compose services follows,
  # therefore they are grouped in to categories as follows:
  #
  #  1. Hosts Commands
  # Services that implement commands that are used to create and bring up the
  # Docker Compose services that emulate hosts in our live server estate and
  # deploy application services to them using Ansible.
  #
  #  2. Network Services
  # These are services that augment to network definitions above to provide
  # network related functions that we require to do our testing.
  #
  #  3. Office only Test Clients
  # Docker Compose services that provide clients that can be used to test the
  # function of the application services that are deployed using Ansible to the
  # hosts in an environment. These are test clients that are only used from the
  # office network, and so their connection to that network is specified in this
  # file.
  #
  #  4. Other Test Clients
  # Test clients that can be used from either the Docker office network or the
  # Docker internet network. Thus the network connection for these services is
  # not specified in this file. Instead two other Docker Compose files,
  # internet.yml and office.yml, are provided to be used when a connection via
  # the Docker internet or Docker office networks is required.

  # -----------------
  # 1. Hosts Commands
  # -----------------

  raise-hosts:
    # Outputs the required dockker and docker-compose commands to bring up the
    # host emulation Docker Compose services for an environment. These commands
    # are piped into a shell to execute them.
    build: ./build/raise-hosts
    environment:
      - MYENV
    network_mode: none
    volumes:
      - ./envs/${MYENV}/services-to-hosts.sh:/usr/src/services-to-hosts.sh

  playbook:
    # Runs the Ansible playbooks that deploy our application services to the
    # host emulation Docker containers for each environment.
    build: ./build/playbook
    environment:
      - MYENV
    volumes:
      - ./envs/${MYENV}/:/environment/:ro
      - ./playbooks/:/playbooks/:ro
      - ./my-roles/:/my-roles:ro
      - ./roles/:/roles/:ro
  # -------------------
  # 2. Network Services
  # -------------------

    networks:
      office:
    cap_add:
      - NET_ADMIN

  router:
    # This service implements a router to route network traffic between the
    # office and internet Docker networks that are defined above.
    build: ./build/router
    env_file:
      - ./envs/${MYENV}/test/network.env
    volumes:
      - ./build/router/templates:/etc/nginx/templates
    networks:
      internet:
        ipv4_address: 10.0.1.254
      office:
        ipv4_address: 10.0.0.254

  # ---------------------------
  # 3. Office only Test Clients
  # ---------------------------

  bconsole:
    # Bacula console
    build: ./build/bconsole
    env_file:
      - ./envs/${MYENV}/test/network.env
    volumes:
      - ./envs/${MYENV}/test/bconsole.conf:/etc/bacula/bconsole.conf
    networks:
      office:

  cadaver:
    # Cadaver WebDav client
    build: ./build/cadaver
    env_file:
      - ./envs/${MYENV}/test/network.env
    networks:
      office:

  dig:
    # Dig DNS lookup tool
    build: ./build/dig
    env_file:
      - ./envs/${MYENV}/test/network.env
    networks:
      office:
    cap_add:
      - NET_ADMIN

  lynx-external:
    build: ./build/lynx
    env_file:
      - ./envs/${MYENV}/test/network.env
    networks:
      internet:

  lynx-internal:
    build: ./build/lynx
    env_file:
      - ./envs/${MYENV}/test/network.env
    networks:
      office:

  # ---------------------
  # 4. Other Test Clients
  # ---------------------

  mutt:
    # Mutt text-based email client
    build: ./build/mutt
    env_file:
      - ./envs/${MYENV}/test/network.env
    volumes:
      - ./envs/${MYENV}/test/mutt:/config
    networks:
      office:
    cap_add:
      - NET_ADMIN

  openssl:
    build: ./build/openssl
    env_file:
      - ./envs/${MYENV}/test/network.env
    networks:
      office:
    cap_add:
      - NET_ADMIN

  proxy-external:
    build: ./build/proxy
    env_file:
      - ./envs/${MYENV}/test/network.env
    command: external
    ports:
      - "3129:3128"
    networks:
      internet:
    cap_add:
      - NET_ADMIN

  proxy-internal:
    build: ./build/proxy
    env_file:
      - ./envs/${MYENV}/test/network.env
    command: internal
    ports:
      - "3128:3128"
    networks:
      office:
    cap_add:
      - NET_ADMIN

  traceroute-internal:
    build: ./build/traceroute
    networks:
      office:
    cap_add:
      - NET_ADMIN

  traceroute-external:
    build: ./build/traceroute
    networks:
      internet:
    cap_add:
      - NET_ADMIN

  swaks:
    # Swiss Army Knife for SMTP
    build: ./build/swaks
    env_file:
      - ./envs/${MYENV}/test/network.env
    networks:
      office:
    cap_add:
      - NET_ADMIN

# There follows a noop service corresponding to all of the services that are
# defined in the now, to-be and distributed environment. These are present so
# that whenever we run the docker-compose command without specifying an
# environment files, and so Docker Compose defaults to the configuration within
# this file, we won't get any orphan container messages and docker-compose
# actions such as stop and rm will be default always affect all this project's
# containers.

  backup-director:
    build: ./build/noop
    image: varilink/noop

  backup-storage:
    build: ./build/noop
    image: varilink/noop

  caldav:
    build: ./build/noop
    image: varilink/noop

  database-external:
    build: ./build/noop
    image: varilink/noop

  database-internal:
    build: ./build/noop
    image: varilink/noop

  dev:
    image: scratch

  dns-external:
    build: ./build/noop
    image: varilink/noop

  dns-internal:
    build: ./build/noop
    image: varilink/noop

  dynamic-dns:
    build: ./build/noop
    image: varilink/noop

  hub:
    build: ./build/noop
    image: varilink/noop

  gateway:
    build: ./build/noop
    image: varilink/noop

  mail:
    build: ./build/noop
    image: varilink/noop

  mail-certificates:
    build: ./build/noop
    image: varilink/noop

  mail-external:
    build: ./build/noop
    image: varilink/noop

  mail-internal:
    build: ./build/noop
    image: varilink/noop

  monitor-gateway:
    build: ./build/noop
    image: varilink/noop

  prod:
    build: ./build/noop
    image: varilink/noop

  reverse-proxy-gateway:
    build: ./build/noop
    image: varilink/noop

  reverse-proxy-external:
    build: ./build/noop
    image: varilink/noop

  reverse-proxy-internal:
    build: ./build/noop
    image: varilink/noop

  wordpress-external:
    build: ./build/noop
    image: varilink/noop

  wordpress-internal:
    build: ./build/noop
    image: varilink/noop
