# ------------------------------------------------------------------------------
# my-roles/backup_client/tasks/stop-bacula-fd.yml
# ------------------------------------------------------------------------------

---

- name: Test if the bacula-fd process is running
  ansible.builtin.shell: pgrep -f '^bacula-fd -f$'
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc !=0 and pgrep_result.rc != 1

- name: Stop bacula-fd process
  ansible.builtin.shell: |-
    echo 'bacula-fd  : Stopping' >> /var/local/services.log
    pkill -f '^bacula-fd -f$'

    n=0
    while [ $n -lt 3 ]; do
      sleep 3
      pgrep -f '^bacula-fd -f$' || \
        echo 'bacula-fd  : Stopped' >> /var/local/services.log && break
      let n=n+1
    done

    if [ $n -eq 3 ]; then
      echo 'bacula-fd  : Failed to stop process' \
        >> /var/local/services.log
    fi
  args:
    executable: /bin/bash
  become: yes
  when: pgrep_result.rc == 0
