# ------------------------------------------------------------------------------
# my-roles/my_mail_internal/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: mail

- ansible.builtin.import_role:
    name: /roles/mail_internal
    tasks_from: install-service
    handlers_from: none

- ansible.builtin.import_role:
    name: /roles/mail_internal
    tasks_from: configure-service
    handlers_from: none
