# ------------------------------------------------------------------------------
# my-roles/mail_internal/tasks/stop-fetchmail.yml
# ------------------------------------------------------------------------------

---

- name: Test if the fetchmail process is running
  ansible.builtin.shell: pgrep -f '^/usr/bin/fetchmail$'
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- name: Stop the fetchmail process if it is running
  ansible.builtin.shell: |-
    echo 'fetchmail  : Stopping' >> '/var/local/services.log'
    pkill -f "^/usr/bin/fetchmail$"
    while true
    do
      sleep 3
      pgrep -f "^/usr/bin/fetchmail$" || break
    done
    echo 'fetchmail  : Stopped' >> '/var/local/services.log'
  become: yes
  when: pgrep_result.rc == 0
