# ------------------------------------------------------------------------------
# my-roles/file_share/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: /roles/file_share
    tasks_from: install

- ansible.builtin.import_role:
    name: /roles/file_share
    tasks_from: configure
