# ------------------------------------------------------------------------------
# my-roles/influxdata/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: /roles/influxdata
