# ------------------------------------------------------------------------------
# my-roles/my_database/tasks/start-mysql.yml
# ------------------------------------------------------------------------------

---

- name: Get the codename of the Debian release on this host
  ansible.builtin.command: lsb_release --codename --short
  register: lsb_release
  changed_when: false

- name: Test if the mysqld (buster) or mariadb (bullseye) process is running
  ansible.builtin.shell: |-
    {% if lsb_release.stdout == 'bullseye' %}
    pgrep -f '^/usr/sbin/mariadbd'
    {% else %}{# buster or stretch #}
    pgrep -f '^/usr/sbin/mysqld'
    {% endif %}
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- block:

    - name: Start the mysqld (buster) or mariadb (bullseye) process
      ansible.builtin.shell: |-
        {% if lsb_release.stdout == 'bullseye' %}
        echo 'mariadbd   : Starting' >> /var/local/services.log
        nohup bash -c "mysqld_safe |& sed -u 's/^/mariadbd   : /'" \
          &>> /var/local/services.log &
        {% else %}{# buster or stretch #}
        echo 'mysqld     : Starting' >> /var/local/services.log
        nohup bash -c "mysqld_safe |& sed -u 's/^/mysqld     : /'" \
          &>> /var/local/services.log &
        {% endif %}
        sleep 3
      args:
        executable: /bin/bash
      become: yes

    - name: Check the mysqld (buster) or mariadb (bullseye) process has started
      # We do this in a separate shell task to the one that we started the
      # process in so that we know that the process survived beyond that shell.
      ansible.builtin.shell: |-
        {% if lsb_release.stdout == 'bullseye' %}
        n=0
        while [ $n -lt 3 ]; do
          pgrep -f '^/usr/sbin/mariadbd' && \
            echo 'mariadbd   : Started' >> /var/local/services.log && break
          let n=n+1
          sleep 3
        done

        if [ $n -eq 3 ]; then
          echo 'mariadbd   : Failed to start process' >> /var/local/services.log
          exit 1
        fi
        {% else %}{# buster or stretch #}
        n=0
        while [ $n -lt 3 ]; do
          pgrep -f '^/usr/sbin/mysqld' && \
            echo 'mysqld     : Started' >> /var/local/services.log && break
          let n=n+1
          sleep 3
        done

        if [ $n -eq 3 ]; then
          echo 'mysqld     : Failed to start process' >> /var/local/services.log
          exit 1
        fi
        {% endif %}
      args:
        executable: /bin/bash

  when: pgrep_result.rc == 1
