# ------------------------------------------------------------------------------
# my-roles/my_database/tasks/start-mariadbd.yml
# ------------------------------------------------------------------------------

---

- name: Test if the mariadbd process is running
  ansible.builtin.command: "pgrep -f '^/usr/sbin/mariadbd'"
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc != 0 and pgrep_result.rc != 1

- block:

    - name: Start the mariadbd process
      ansible.builtin.shell: |-
        echo 'mariadbd   : Starting' >> /var/local/services.log
        nohup bash -c "mysqld_safe |& sed -u 's/^/mariadbd   : /'" \
          &>> /var/local/services.log &
        sleep 3
      args:
        executable: /bin/bash
      become: yes

    - name: Check the mariadbd process has started
      # We do this in a separate shell task to the one that we started the
      # process in so that we know that the process survived beyond that shell.
      ansible.builtin.shell: |-
        n=0
        while [ $n -lt 3 ]; do
          pgrep -f '^/usr/sbin/mariadbd' && \
            echo 'mariadbd   : Started' >> /var/local/services.log && break
          let n=n+1
          sleep 3
        done

        if [ $n -eq 3 ]; then
          echo 'mariadbd   : Failed to start process' >> /var/local/services.log
          exit 1
        fi
      args:
        executable: /bin/bash

  when: pgrep_result.rc == 1
