# ------------------------------------------------------------------------------
# my-roles/my_database/tasks/stop-mariadbd.yml
# ------------------------------------------------------------------------------

---

- name: Test if the mariadbd process is running
  ansible.builtin.command: "pgrep -f '^/usr/sbin/mariadbd'"
  register: pgrep_result
  changed_when: false
  failed_when: pgrep_result.rc !=0 and pgrep_result.rc != 1

- name: Stop the mariadbd process
  # NOTE: The mysqld_safe command creates a process whose "CMD" in ps output
  # is "/bin/sh /usr/bin/mysqld_safe". That process does not respond to a
  # SIGKILL. The process that accepts a SIGKILL is a child of this process
  # whose "CMD" starts with "/usr/sbin/mariadbd".
  ansible.builtin.shell: |-
    echo 'mariadbd   : Stopping' >> /var/local/services.log
    pkill -f '^/usr/sbin/mariadbd'

    n=0
    while [ $n -lt 3 ]; do
      sleep 3
      pgrep -f '^/usr/sbin/mariadbd' || \
        echo 'mariadbd   : Stopped' >> /var/local/services.log && break
      let n=n+1
    done

    if [ $n -eq 3 ]; then
      echo 'mariadbd   : Failed to stop process' \
        >> /var/local/services.log
    fi
  args:
    executable: /bin/bash
  become: yes
  when: pgrep_result.rc == 0
