# ------------------------------------------------------------------------------
# envs/now/inventory/host_vars/prod1.yml
# ------------------------------------------------------------------------------

---

ansible_host: 10.0.1.102

# Backup client passwords, which of course would be sensitive data in a live
# environment.
backup_client_director_password: PRFnSTRZCfvFLmRurvaSEJdM3NelguMWe
backup_client_monitor_password: 81xqw5S1Krh86ARpAa4IgUIZxsp166s4f
