# ------------------------------------------------------------------------------
# envs/to-be/docker-compose.yml
# ------------------------------------------------------------------------------

# Host Docker Compose services for the "to-be" test environment.

version: "3.7"

services:

  # office network

  dev:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_dev
    hostname: dev
    networks:
      office:
        ipv4_address: 10.0.0.101
    cap_add:
      - NET_ADMIN

  gateway:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_gateway
    hostname: gateway
    networks:
      office:
        ipv4_address: 10.0.0.102
    cap_add:
      - NET_ADMIN

  hub:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_hub
    hostname: hub
    volumes:
      - bacula-home:/var/lib/bacula/
    networks:
      office:
        ipv4_address: 10.0.0.103
    cap_add:
      - NET_ADMIN

  # internet

  dns-external:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_dns-external
    hostname: dns-external
    networks:
      internet:
        ipv4_address: 10.0.1.101
    cap_add:
      - NET_ADMIN

  mail-external:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_mail-external
    hostname: mail-external
    networks:
      internet:
        ipv4_address: 10.0.1.102
    cap_add:
      - NET_ADMIN

  prod:
    build: build/sshd
    image: varilink/services/sshd:bullseye
    container_name: services_prod
    hostname: prod
    networks:
      internet:
        ipv4_address: 10.0.1.103
    cap_add:
      - NET_ADMIN

volumes:
  bacula-home:
