# ------------------------------------------------------------------------------
# my-roles/my_mail_external/tasks/main.yml
# ------------------------------------------------------------------------------

---

- ansible.builtin.import_role:
    name: mail

- ansible.builtin.import_role:
    tasks_from: install
    vars_from: none
    name: /roles/mail_external

- ansible.builtin.import_role:
    tasks_from: configure
    vars_from: none
    name: /roles/mail_external
